spring:
  application:
    name: translator
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 513454
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

integration:
  translate:
    url: https://translate.api.cloud.yandex.net/translate/v2/translate
  auth:
    url: https://iam.api.cloud.yandex.net/iam/v1/tokens
  multithreading:
    corePoolSize: 3
    maxPoolSize: 500
    queueCapacity: 25
